# Generated by Django 4.2.6 on 2023-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=1000)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
