# Generated by Django 4.2.6 on 2023-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.TextField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], default='NONE'),
        ),
    ]
