# Generated by Django 4.2.6 on 2023-12-14 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
