# Generated by Django 4.2.6 on 2023-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_boards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('INVALID', 'Choose Type'), ('Private', 'Private'), ('Team', 'Team')], default='INVALID', max_length=11),
        ),
        migrations.AlterField(
            model_name='board',
            name='team_emails',
            field=models.TextField(default='Enter team emails here if necessary, seperated by commas.'),
        ),
    ]
