# Generated by Django 4.2.6 on 2023-11-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
        ('tasks', '0003_alter_board_options_remove_board_created_at_and_more'),
    ]

    operations = [
    ]
